name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install prerequirements
      run: |
        sudo apt-get install -y python3-pip python3-wheel python3-setuptools build-essential nodejs
        sudo pip3 install --system cwltest cwl-runner ruamel.yaml==0.15.97
    - name: Run tests
      id: run-tests
      uses: common-workflow-lab/run-tests@v1
      with:
        test-list: test.yml
        runner: cwltool
        timeout: 30
